### ISSUE TITLE
Ara has an issue

### ISSUE THREAD

**Issue by MurphyPicard** [ga-wdi-pvd/project2-gallery#1]
My portfolio page, which will look better someday - 
https://murphypicard.github.io/ 

JustPlayIt!
http://ara-justplay.herokuapp.com/

Kind of fun to make once I restarted the third time.

**Comment by estermer** [comment]
Scoring 0 - 3
Your Score: 1

Ara,

Glad to see your work here.

Recognize that the score of one is not bad, it means you met all the minimum requirements for the project.

You have 2 models and Full CRUD for each. Your styling is personal but not reaching. Your code is clean and shows that you understand how to take advantage of building Rails Apps.

Server side applications are hard and take practice to get the hang of and you have shown that you have understood a complex concept in a quick period of time.

Cannot wait to see how you do with project 3. Great Job!

-Eric
