### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by jtellis** [ga-wdi-pvd/project2-gallery#10]
https://github.com/jtellis/determinedme

**Comment by tvcrawley** [comment]
# Project Evaluation

| Category                        | Incomplete      ☹️                          | Progressing         👍                      | Performing        ✅                        | Excelling      😃                           |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          |  | | | Includes many well-structured models, and advanced functionality such as authorization, 3rd-party API integration, or technology not covered in class. |
| Creativity and Interface        |  |  |  | The app is fully responsive, incorporates outside technologies such as Flexbox.  App incorporates modern UI themes, and adds unique  flair. |
| Code Quality                    |     |  |  | No major code quality issues, makes use of Ruby best practices appropriately, and follows techniques such as separation of concerns, abstraction, and encapsulation. |
| Functionality    |  |  | | App has advanced functionality that works with minimal errors, and may make use of advanced tools such as APIs, plugins, etc.  |
| Planning / Process / Submission |  | |  | Submission includes everything in previous category, as well as evidence of  planning tools, such as Trello, and, incorporates workflows such as feature branching, code review, github issue / user story tracking, and justification of technical decisions. |

**Comment by tvcrawley** [comment]
@jtellis Great project! 🎉  

Functionality, code quality, styling, and documentation were all above average (hence the excelling above). 
Your plans for future implementation are very good push goals and will only enhance the work you've already done. Also, it demonstrates to employers you enjoy improving previously done work.

_This project was accessed using the [evaluation](https://github.com/ga-wdi-pvd/project2/blob/master/evaluation.md) included in the project 2 repo._
