### ISSUE TITLE
awanderlyss WEEK? DAY01 Project#1

### ISSUE THREAD

**Issue by awanderlyss** [ga-wdi-pvd/project2-gallery#12]
Here is the app Deployed on Heroku:
https://gamrbuddy.herokuapp.com/

Here is the gitHub repo of the project:
https://github.com/awanderlyss/gamrbuddy

Here is the project in my "portfolio" :
https://awanderlyss.github.io

**Comment by JosephinaTavera** [comment]
😕  Tried accessing portfolio with link above , and received Server error message   404 - File or directory not found

Loved the concept, and look forward to seeing it with full CRUD compatibility.       

Make sure to create a planning directory with your ERD, wireframes and user stories.   

Revise readme document with explanations of the technologies used, the approach taken, installation instructions, unsolved problems, etc

**Comment by JosephinaTavera** [comment]
# Project Evaluation

| Category                        | Incomplete                               | Progressing                              | Performing                               | Excelling                                |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          | 0 Models, or partial CRUD on at least 1 model. |  | |  |
| Creativity and Interface        |  | The app is styled and has an interface of value to the end user: it is not just a nav bar and an index page | | |
| Code Quality                    | |  | Code is well-formatted, well-named, and contains few style / quality issues | |
| Functionality    | Application contains minimal functionality |  | |  |
| Planning / Process / Submission | No submission received, or submission does not contain basic documentation of planning (ERD, wireframes, commit history, etc) |  | |  |
