### ISSUE TITLE
Julie Khun - Project 2

### ISSUE THREAD

**Issue by missjuliekhun** [ga-wdi-pvd/project2-gallery#13]
Here is my app on Heroku: https://travelwithme-heroku-deploy.herokuapp.com/
Project Repo: https://github.com/missjuliekhun/travel_blog
Portfolio is a work in progress.

**Comment by tvcrawley** [comment]
# Project Evaluation

| Category                        | Incomplete   ☹️                             | Progressing       👍                        | Performing      ✅                        | Excelling        😄                           |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          | |At least 1 model incorporates `GET`, `POST`, `PUT`, and `DELETE` routes, but no associations. | | |
| Creativity and Interface        | Zero or Minimal custom styles or interface.  |  |  |  |
| Code Quality                    | Minimal custom or non-scaffolded code is present.       |  |  |  |
| Functionality    | Application contains minimal functionality. |  |  |  |
| Planning / Process / Submission |  | App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality, and/or ERD. |  |  |

**Comment by tvcrawley** [comment]
@missjuliekhun This application does not meet the minimal specifications laid out in the [project 2 repo](https://github.com/ga-wdi-pvd/project2).

On revisiting, add in the functionality that will have it perform at the base level and move on from there. Also, remember you have the instructors and your classmates to help you, so don't hesitate to ask questions.

**Comment by tvcrawley** [comment]
Project was accessed using the [evaluation](https://github.com/ga-wdi-pvd/project2/blob/master/evaluation.md) included in the project 2 repo

**Comment by missjuliekhun** [comment]
Thank you for the feedback, Toni ❤️
