### ISSUE TITLE
Project #2

### ISSUE THREAD

**Issue by DomreyCS** [ga-wdi-pvd/project2-gallery#2]
https://github.com/DaraHoy/FoodPlugr
Don't have a portfolio site yet.

**Comment by estermer** [comment]
Scoring 0 - 3
Your Score: 1

Dara,

I remember looking at your application when you presented it and it was not fully complete. It is hard to tell if it is complete just by looking at the code without it being deployed.

Make sure you get this deployed, not just for this classes purposes but for your portfolio to show your work to potential employers.

Looking at what you were able to get done in terms of code, it is clean and shows you generally understand Rails. You met the minimum requirement of 2 models, incorporated the use of a DB, and used ERB to display your change in data.

I like your idea btw, If you get a chance, maybe run with it and think through how you can create this for real and get a community going around it!

You met the minimum requirements and therefore I gave you a 1. Get it deployed and looking forward to you showing your stuff with project 3.

-Eric
