### ISSUE TITLE
Project #2

### ISSUE THREAD

**Issue by patrickthesailorman** [ga-wdi-pvd/project2-gallery#3]
My portfolio page,
[patrickcmccarty.com](www.patrickcmccarty.com)
My project #2 is linked to that page or get it directly here,
[Postit!](https://patsapp.herokuapp.com)

**Comment by patrickthesailorman** [comment]
Git hub portfolio page,
[my Github](https://github.com/patrickthesailorman)

**Comment by JosephinaTavera** [comment]
Loved the simplicity of the app.   

Revise readme document with explanations of the technologies used, the approach taken, installation instructions, unsolved problems, etc

Good amount of commits.   

Adding more comments will be beneficial to understanding what the code is doing.

**Comment by JosephinaTavera** [comment]
# Project Evaluation

| Category                        | Incomplete                               | Progressing                              | Performing                               | Excelling                                |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          |  |  | The app contains 2 models, with at least 1 association. At least 1 model is full CRUD. |  |
| Creativity and Interface        | | | | The app is fully responsive, incorporates outside technologies such as Flexbox.  App incorporates modern UI themes, and adds unique  flair. |
| Code Quality                    | | | Code is well-formatted, well-named, and contains few style / quality issues | |
| Functionality    |  |  | Application contains no major errors |  |
| Planning / Process / Submission |  | App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality ||  |
