### ISSUE TITLE
Project #2 - Comparative

### ISSUE THREAD

**Issue by RFSync** [ga-wdi-pvd/project2-gallery#4]
https://github.com/myztajay/Comparative

**Comment by JosephinaTavera** [comment]
🤔    Missing link to your portfolio page

Otherwise GREAT JOB!      

Nice healthy dose of commits,  more comments in code will help you ( or anyone ) acclimate to what purpose sections of the code serve

**Comment by JosephinaTavera** [comment]
# Project Evaluation

| Category                        | Incomplete                               | Progressing                              | Performing                               | Excelling                                |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          |  | | The app contains 2 models, with at least 1 association. At least 1 model is full CRUD. |  |
| Creativity and Interface        | | |  | The app is fully responsive, incorporates outside technologies such as Flexbox.  App incorporates modern UI themes, and adds unique  flair. |
| Code Quality                    | | | | No major code quality issues, makes use of Ruby best practices appropriately, and follows techniques such as separation of concerns, abstraction, and encapsulation |
| Functionality    | |  |  | App has advanced functionality that works with minimal errors, and may make use of advanced tools such as APIs, plugins, etc.  |
| Planning / Process / Submission | | | Submission contains clear evidence of planning, adequate documentation, include all from previous category, as well as additional information such as unsolved issues. | |
