### ISSUE TITLE
mwb86 Project 2

### ISSUE THREAD

**Issue by mwb86** [ga-wdi-pvd/project2-gallery#6]
My project 2 repository https://github.com/mwb86/project2

Portfolio https://mwb86.github.io/

**Comment by estermer** [comment]
Scoring 0 - 3
Your Score: 3

Mason great job on this project. Your styling could use a little work but all in all you put your personal spin on it and you showed some skill.

In terms of your models, You have 4 which is more than our minimum and it looks as though you have full CRUD on all of them (except comments but that is ok).

I loved the little timestamp feature that shows anyone how long ago the comment was created.

Your code is about as clean and concise as it can get for a beginner and for Rails.

Great Job, Looking forward to seeing how you and your team will perform for project 3.

-Eric
