### ISSUE TITLE
Anusone Nanthavongsa's Project 2

### ISSUE THREAD

**Issue by ahnuce** [ga-wdi-pvd/project2-gallery#7]
Here is the app Deployed on Heroku
https://anume.herokuapp.com/

Here is the gitHub repo of the project.
https://github.com/ahnuce/anume

Here is my portfolio page
https://ahnuce.github.io

**Comment by JosephinaTavera** [comment]
😍   Anume   

Enjoyed the topic chosen, and your idea for the project.   

Make sure to create a planning directory with your ERD, wireframes and user stories.

Revise readme document with explanations of the technologies used, the approach taken, installation instructions, unsolved problems, etc

Aim to have more commits and more comments to code.     If you would like to have another developer help with this project that informations would be greatly appreciated.

**Comment by JosephinaTavera** [comment]
# Project Evaluation

| Category                        | Incomplete                               | Progressing                              | Performing                               | Excelling                                |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          | |  | The app contains 2 models, with at least 1 association. At least 1 model is full CRUD. | |
| Creativity and Interface        | |  | | The app is fully responsive, incorporates outside technologies such as Flexbox.  App incorporates modern UI themes, and adds unique  flair. |
| Code Quality                    | | | Code is well-formatted, well-named, and contains few style / quality issues |  |
| Functionality    | | | Application contains no major errors | |
| Planning / Process / Submission | No submission received, or submission does not contain basic documentation of planning (ERD, wireframes, commit history, etc) |  | | |
