### ISSUE TITLE
dmozzoni - Project2

### ISSUE THREAD

**Issue by dmozzoni** [ga-wdi-pvd/project2-gallery#8]
Project 2 - Butterflying Life List
https://github.com/dmozzoni/life
http://butterfly-life.herokuapp.com

Portfolio Page (incomplete)
https://github.com/dmozzoni/Portfolio
https://dmozzoni.github.io/Portfolio/

**Comment by missjuliekhun** [comment]
Wow David! Your content is amazing.

**Comment by JosephinaTavera** [comment]
Amazing work in the time provided.    

Great history of commits &  comments .     Only missing the planning directory containing an ERD mapping out your project domain, wireframes, user stories.

**Comment by JosephinaTavera** [comment]
# Project Evaluation

| Category                        | Incomplete                               | Progressing                              | Performing                               | Excelling                                |
| ------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- | ---------------------------------------- |
| Technical Requirements          |  |  |  | Includes many well-structured models, and advanced functionality such as authorization, 3rd-party API integration, or other technology not covered in class |
| Creativity and Interface        |  |  |  | The app is fully responsive, incorporates outside technologies such as Flexbox.  App incorporates modern UI themes, and adds unique  flair. |
| Code Quality                    | | | |No major code quality issues, makes use of best practices appropriately, and follows techniques such as separation of concerns, abstraction, and encapsulation |
| Functionality    |  |  |  | App has advanced functionality that works with minimal errors, and may make use of advanced tools such as APIs, plugins, etc.  |
| Planning / Process / Submission |  |  | Submission contains evidence of planning, adequate documentation,  as well as additional information such as unsolved issues. | |
